# Generated by Django 5.2.6 on 2025-10-01 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "displayname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="显示名称"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "is_muted",
                    models.BooleanField(default=False, verbose_name="是否禁言"),
                ),
                (
                    "mute_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="禁言结束时间"
                    ),
                ),
                ("mute_reason", models.TextField(blank=True, verbose_name="禁言原因")),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="是否封禁"),
                ),
                (
                    "ban_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="封禁结束时间"
                    ),
                ),
                ("ban_reason", models.TextField(blank=True, verbose_name="封禁原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="封禁操作者",
                    ),
                ),
                (
                    "muted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="muted_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="禁言操作者",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
