# Generated by Django 5.2.6 on 2025-09-18 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="PostCategory",
        ),
        migrations.AlterModelOptions(
            name="postcategory",
            options={"verbose_name": "文章分类", "verbose_name_plural": "文章分类"},
        ),
    ]
