# Generated by Django 5.2.6 on 2025-09-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_html",
            field=models.TextField(blank=True, verbose_name="HTML内容"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Markdown内容"),
        ),
    ]
