# Generated by Django 5.2.6 on 2025-09-19 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_options_post_is_pinned_post_pinned_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="post",
            name="pinned_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.comment",
                verbose_name="被点赞评论",
            ),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.postcategory",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="被点赞文章",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("user", "comment")},
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("user", "post")},
        ),
    ]
