# Generated by Django 5.2.6 on 2025-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_postfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorites_count",
            field=models.PositiveIntegerField(default=0, verbose_name="收藏数"),
        ),
    ]
